import { useMemo, useState } from 'react'
import './App.css'

const products = [
  { id: '515291', article: '200300285_', name: 'Автоматический выключатель ВА47-100 3P 160А', brand: 'EKF', type: 'Низковольтная аппаратура', price: '64 920 ₸', quantity: 23, image: 'https://images.unsplash.com/photo-1555963966-b7ae5404b6ed?auto=format&fit=crop&w=700&q=80', warning: 'Номинальный ток требует уточнения: 160 А в названии, 250 А в структурном свойстве.', characteristics: [['Полюса', '3P'], ['Напряжение', '400 В'], ['Ток', 'Требует уточнения'], ['Отключающая способность', '10 кА']] },
  { id: '48783', article: '200100442_', name: 'Выключатель автоматический ВА47-100 3P 100А', brand: 'EKF', type: 'Низковольтная аппаратура', price: '42 700 ₸', quantity: 12, image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=700&q=80', characteristics: [['Полюса', '3P'], ['Напряжение', '400 В'], ['Ток', '100 А'], ['Отключающая способность', '10 кА']] },
  { id: '23466', article: '300410120_', name: 'Кабель силовой ВВГнг(А)-LS 3х2.5', brand: 'ЭКСПЕРТ-КАБЕЛЬ', type: 'Кабель / Провод', price: '385 ₸ / м', quantity: 0, image: 'https://images.unsplash.com/photo-1617897711388-0480c3d7d6d8?auto=format&fit=crop&w=700&q=80', characteristics: [['Жилы', '3'], ['Сечение', '2.5 мм²'], ['Напряжение', '0.66 кВ'], ['Длина', 'Бухта']] },
]
const suggestions = ['Найди автомат 3P 160А', 'Что есть в наличии в Астане?', 'Подбери замену для кабеля']

function App() {
  const [query, setQuery] = useState('')
  const [selectedId, setSelectedId] = useState('515291')
  const [chatOpen, setChatOpen] = useState(true)
  const [message, setMessage] = useState('')
  const [messages, setMessages] = useState([{ from: 'assistant', text: 'Здравствуйте! Я помогу найти электротехнические товары, проверить наличие и подобрать замену по подтверждённым данным.' }, { from: 'assistant', text: 'Уже открыла карточку автомата EKF. У него есть один параметр, который нужно уточнить.' }])
  const [cart, setCart] = useState([])
  const [proposal, setProposal] = useState(null)
  const [compareOpen, setCompareOpen] = useState(false)
  const filteredProducts = useMemo(() => { if (!query.trim()) return products; const value = query.toLowerCase(); return products.filter((product) => `${product.id} ${product.article} ${product.name} ${product.type}`.toLowerCase().includes(value)) }, [query])
  const selectedProduct = products.find((product) => product.id === selectedId) || products[0]
  const alternative = products[1]

  function sendMessage(text = message) {
    const cleanText = text.trim(); if (!cleanText) return
    setMessages((current) => [...current, { from: 'user', text: cleanText }]); setMessage('')
    const lower = cleanText.toLowerCase(); let answer = 'Проверила демо-выборку. Уточните, пожалуйста, ID, артикул или нужный параметр товара.'
    if (lower.includes('добав') || lower.includes('корз')) { setProposal({ product: selectedProduct, quantity: 2 }); answer = `Могу добавить 2 шт. «${selectedProduct.name}». Сейчас доступно: ${selectedProduct.quantity} шт. Подтвердите добавление кнопкой ниже.` }
    else if (lower.includes('замен') || selectedProduct.quantity === 0) { setCompareOpen(true); answer = `У товара нет подтверждённого остатка. Нашла вариант для сравнения: ${alternative.name}. Совпадают полюса, напряжение и отключающая способность.` }
    else if (lower.includes('цен') || lower.includes('налич')) answer = `Цена: ${selectedProduct.price}. Остаток: ${selectedProduct.quantity} шт. Данные показаны по последней подробной карточке EKT.`
    else if (lower.includes('характер') || lower.includes('ток')) answer = selectedProduct.warning || `Подтверждённые характеристики: ${selectedProduct.characteristics.map(([key, value]) => `${key} — ${value}`).join(', ')}.`
    window.setTimeout(() => setMessages((current) => [...current, { from: 'assistant', text: answer }]), 250)
  }
  function confirmAdd() { if (!proposal) return; setCart((current) => [...current, { ...proposal.product, quantity: proposal.quantity }]); setMessages((current) => [...current, { from: 'assistant', text: 'Готово. Позиция добавлена в демо-корзину. Перед реальным оформлением остаток и цена должны быть проверены повторно через API.' }]); setProposal(null) }

  return <div className={`app-shell ${chatOpen ? 'chat-active' : ''}`}>
    <div className="utility-bar"><div>⌖ Астана</div><div className="utility-links"><span>Личный кабинет</span><span>B2B · EKT PRO</span><span>Покупателям⌄</span><span>Оставить заявку</span><strong>+7 (700) 222-05-14</strong></div></div>
    <header className="main-header"><div className="brand"><span>ГРУППА КОМПАНИЙ</span><b>ЭЛЕКТРОКОМПЛЕКТ</b></div><button className="catalog-button">Каталог <span>☷</span></button><label className="global-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Поиск по названию, ID или артикулу" /><kbd>⌘ K</kbd></label><div className="header-actions"><span>⇄ Сравнить</span><span>♡ Избранное</span><button onClick={() => setChatOpen(true)}>▱ Корзина <i>{cart.length}</i></button></div></header>
    <main><section className="welcome-row"><div><p className="eyebrow">EKT SMART SEARCH <span>ДЕМО-РЕЖИМ</span></p><h1>Подберём нужное.<br /><em>Проверим каждую деталь.</em></h1><p className="intro">Умный помощник по электротехническим товарам. Находит по каталогу EKT, объясняет различия и помогает собрать заказ.</p></div><div className="trust-panel"><div className="pulse-dot"></div><div><b>Данные проверены</b><span>Цены и остатки из карточек EKT</span></div><small>›</small></div></section><div className="search-wrap"><span className="search-icon">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && sendMessage(query)} placeholder="Например, автомат 3P или 200300285_" /><button onClick={() => sendMessage(query || 'Покажи товары')}>Найти <span>↗</span></button></div><div className="quick-row"><span>Популярное:</span>{suggestions.map((item) => <button key={item} onClick={() => { setQuery(item); sendMessage(item) }}>{item}</button>)}</div>
      <div className="content-grid"><section className="catalog-column"><div className="section-heading"><div><span className="section-kicker">КАТАЛОГ EKT · {filteredProducts.length} ПОЗИЦИИ</span><h2>Товары для вашего проекта</h2></div><div className="view-toggle"><button className="active">▦</button><button>☷</button></div></div>{filteredProducts.length === 0 && <div className="empty-state"><span>⌕</span><h3>Ничего не нашли</h3><p>Попробуйте ID, артикул или название товара.</p></div>}<div className="product-list">{filteredProducts.map((product) => <article className={`product-card ${selectedId === product.id ? 'selected' : ''}`} key={product.id} onClick={() => setSelectedId(product.id)}><div className="product-image"><img src={product.image} alt="" /><span className={product.quantity ? 'in-stock' : 'out-stock'}>{product.quantity ? 'В наличии' : 'Нет в наличии'}</span></div><div className="product-info"><span className="product-type">{product.type}</span><h3>{product.name}</h3><div className="meta"><span>ID {product.id}</span><span>Арт. {product.article}</span></div><div className="product-bottom"><b>{product.price}</b><span className={product.quantity ? 'stock' : 'muted'}>{product.quantity ? `${product.quantity} шт. на складах` : 'Остаток 0 шт.'}</span></div></div><button className="card-arrow" aria-label="Открыть товар">↗</button></article>)}</div></section>
        <aside className="detail-column"><div className="detail-top"><span className="section-kicker">ПОДРОБНАЯ КАРТОЧКА</span><div className="detail-actions"><button>♡</button><button>⋯</button></div></div><div className="detail-image"><img src={selectedProduct.image} alt="" /><span className="verified">✓ Данные подтверждены</span></div><span className="product-type">{selectedProduct.type}</span><h2>{selectedProduct.name}</h2><div className="detail-meta"><span>Бренд <b>{selectedProduct.brand}</b></span><span>Артикул <b>{selectedProduct.article}</b></span></div><div className="price-row"><div><small>Цена за единицу</small><strong>{selectedProduct.price}</strong></div><div className={selectedProduct.quantity ? 'availability' : 'availability unavailable'}><i></i>{selectedProduct.quantity ? `В наличии · ${selectedProduct.quantity} шт.` : 'Нет в наличии'}</div></div>{selectedProduct.warning && <div className="warning"><span>!</span><p><b>Нужно внимание</b>{selectedProduct.warning}</p></div>}<div className="characteristics"><div className="subheading"><b>Характеристики</b><span>Все параметры ↗</span></div>{selectedProduct.characteristics.map(([key, value]) => <div className="characteristic" key={key}><span>{key}</span><b className={value.includes('уточ') ? 'needs-check' : ''}>{value}</b></div>)}</div>{selectedProduct.quantity === 0 && <button className="outline-button" onClick={() => { setCompareOpen(true); setChatOpen(true) }}>Подобрать замену <span>→</span></button>}<a className="ekt-link" href="https://ekt.kz" target="_blank" rel="noreferrer">Открыть на ekt.kz ↗</a></aside></div>
      {compareOpen && <section className="compare-section"><div className="section-heading"><div><span className="section-kicker">ПРОВЕРЕННЫЙ ПОДБОР</span><h2>Возможная замена</h2></div><button className="close-button" onClick={() => setCompareOpen(false)}>×</button></div><div className="compare-card"><div className="compare-product"><img src={alternative.image} alt="" /><div><span className="product-type">{alternative.type}</span><h3>{alternative.name}</h3><span className="stock">✓ В наличии · {alternative.quantity} шт.</span></div></div><div className="match-score"><strong>3/4</strong><span>параметра совпадает</span></div><div className="compare-note"><b>Почему подходит</b><p>Совпадают полюса, напряжение и отключающая способность. Номинальный ток отличается, поэтому перед монтажом нужна проверка специалиста.</p></div></div></section>}
    </main>
    <button className={`chat-launcher ${chatOpen ? 'hidden' : ''}`} onClick={() => setChatOpen(true)}>✦ <span>Спросить EKT AI</span></button>
    {chatOpen && <aside className="chat-panel"><div className="chat-header"><div className="assistant-avatar">✦</div><div><b>EKT AI</b><span>Ассистент-консультант <i></i></span></div><button onClick={() => setChatOpen(false)}>×</button></div><div className="chat-context"><span>◉</span> Анализирую каталог EKT <b>в реальном времени</b></div><div className="messages">{messages.map((item, index) => <div className={`message ${item.from}`} key={`${item.text}-${index}`}>{item.from === 'assistant' && <span className="mini-avatar">✦</span>}<p>{item.text}</p></div>)}{proposal && <div className="proposal"><span className="proposal-label">ПРЕДЛОЖЕНИЕ</span><b>{proposal.quantity} шт. · {proposal.product.name}</b><span>{proposal.product.price} за единицу</span><button onClick={confirmAdd}>Подтвердить добавление <span>→</span></button><button className="cancel-proposal" onClick={() => setProposal(null)}>Отмена</button></div>}<div className="chat-suggestions">{suggestions.slice(0, 2).map((item) => <button key={item} onClick={() => sendMessage(item)}>{item}</button>)}</div></div><form className="chat-input" onSubmit={(event) => { event.preventDefault(); sendMessage() }}><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Напишите вопрос..." /><button aria-label="Отправить">↑</button></form><div className="chat-footnote">Ответы основаны на подтверждённых данных · <u>Подробнее</u></div></aside>}
  </div>
}

export default App
